import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import TopCorner from "@/components/top-corner";
import BottomCorner from "@/components/bottom-corner";
import Sidebar from "@/components/sidebar";
import { ModalProvider } from "@/providers/modal-provider";
import Apresentacao from "@/components/apresentacao";

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portifólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex items-start md:items-center justify-center w-screen h-screen">
          <div className="container">
            <TopCorner />
            <BottomCorner />
            <ModalProvider />

            <div className="flex lg:flex-row flex-col justify-between mt-4">
              {children}
              <Apresentacao />
              <Sidebar />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
