import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import TopCorner from "@/components/top-corner";
import BottomCorner from "@/components/bottom-corner";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import { SeparatorHorizontal } from "lucide-react";

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex items-center justify-center w-screen h-screen">
          <div className="container">
            <TopCorner />
            <BottomCorner />

            <div className="flex justify-between mt-4">
              {children}
              <Sidebar />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
